---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  bootstrap: true
  targetNamespace: cilium-system
  createNamespace: true
  valuesContent: |-

    debug:
      enabled: true
    operator:
      replicas: 1

    # will be done on startup of node
    cgroup:
      hostRoot: /sys/fs/cgroup
      autoMount:
        enabled: false

    # remove the kube-proxy to save resources
    kubeProxyReplacement: true
    # needed by kubeProxyReplacement and only possible, because k3s exposes it
    # on every node, not only servers, via a load-balancer
    # see: https://docs.k3s.io/architecture?_highlight=supervisor#how-agent-node-registration-works
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6444
    # route pod traffic directly in docker network without vxlan
    routingMode: native
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 10.0.0.0/8

    # provide traffic flow analysis
    hubble:
      metrics:
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
      relay:
        # -- Enable Hubble Relay (requires hubble.enabled=true)
        enabled: true
      ui:
        # -- Whether to enable the Hubble UI.
        enabled: true
        standalone:
          enabled: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble
  namespace: cilium-system
spec:
  rules:
  - host: hubble.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hubble-ui
            port: 
              number: 80
