apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-

    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    service:
      type: ClusterIP
    ports:
      web:
        hostPort: 80
        forwardedHeaders:
          enabled: true
          trustedIPs:
            - 10.0.0.0/8
      websecure:
        hostPort: 443
        forwardedHeaders:
          enabled: true
          trustedIPs:
            - 10.0.0.0/8
